# Generated by Django 2.1.7 on 2019-03-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_auto_20190301_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='Label',
            field=models.ForeignKey(blank=True, on_delete=models.SET(''), related_name='Label', to='trello.Label'),
        ),
    ]
