# Generated by Django 2.1.7 on 2019-03-01 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0003_auto_20190301_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Label', to='trello.Label'),
        ),
    ]
