# Generated by Django 2.1.7 on 2019-03-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0004_auto_20190301_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
