# Generated by Django 2.1.7 on 2019-03-02 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trello', '0009_auto_20190302_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='created_by',
        ),
        migrations.AddField(
            model_name='board',
            name='created_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='card',
            name='Members',
        ),
        migrations.AddField(
            model_name='card',
            name='Members',
            field=models.ManyToManyField(blank=True, default='', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='list',
            name='created_by',
        ),
        migrations.AddField(
            model_name='list',
            name='created_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
