# Generated by Django 2.1.7 on 2019-03-02 11:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0012_auto_20190302_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 11, 11, 38, 46947, tzinfo=utc)),
        ),
    ]
