# Generated by Django 2.1.7 on 2019-03-03 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0016_auto_20190302_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 3, 10, 59, 33, 7856)),
        ),
    ]
